module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert(
      'matches',
      [
        {
          homeTeam: 16,
          homeTeamGoals: 1,
          awayTeam: 8,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 9,
          homeTeamGoals: 1,
          awayTeam: 14,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 4,
          homeTeamGoals: 3,
          awayTeam: 11,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 3,
          homeTeamGoals: 0,
          awayTeam: 2,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 7,
          homeTeamGoals: 1,
          awayTeam: 10,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 5,
          homeTeamGoals: 1,
          awayTeam: 13,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 12,
          homeTeamGoals: 2,
          awayTeam: 6,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 15,
          homeTeamGoals: 0,
          awayTeam: 1,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 1,
          homeTeamGoals: 0,
          awayTeam: 12,
          awayTeamGoals: 3,
          inProgress: false,
        },
        {
          homeTeam: 2,
          homeTeamGoals: 0,
          awayTeam: 9,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 13,
          homeTeamGoals: 1,
          awayTeam: 3,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 6,
          homeTeamGoals: 0,
          awayTeam: 4,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 8,
          homeTeamGoals: 2,
          awayTeam: 5,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 14,
          homeTeamGoals: 2,
          awayTeam: 16,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 10,
          homeTeamGoals: 0,
          awayTeam: 15,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 11,
          homeTeamGoals: 0,
          awayTeam: 7,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 1,
          homeTeamGoals: 2,
          awayTeam: 8,
          awayTeamGoals: 3,
          inProgress: false,
        },
        {
          homeTeam: 12,
          homeTeamGoals: 4,
          awayTeam: 5,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 11,
          homeTeamGoals: 2,
          awayTeam: 2,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 7,
          homeTeamGoals: 0,
          awayTeam: 9,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 6,
          homeTeamGoals: 3,
          awayTeam: 13,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 4,
          homeTeamGoals: 3,
          awayTeam: 3,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 15,
          homeTeamGoals: 2,
          awayTeam: 16,
          awayTeamGoals: 3,
          inProgress: false,
        },
        {
          homeTeam: 10,
          homeTeamGoals: 2,
          awayTeam: 14,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 2,
          homeTeamGoals: 0,
          awayTeam: 6,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 13,
          homeTeamGoals: 1,
          awayTeam: 1,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 5,
          homeTeamGoals: 1,
          awayTeam: 15,
          awayTeamGoals: 2,
          inProgress: false,
        },
        {
          homeTeam: 16,
          homeTeamGoals: 3,
          awayTeam: 7,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 9,
          homeTeamGoals: 0,
          awayTeam: 4,
          awayTeamGoals: 4,
          inProgress: false,
        },
        {
          homeTeam: 3,
          homeTeamGoals: 0,
          awayTeam: 12,
          awayTeamGoals: 4,
          inProgress: false,
        },
        {
          homeTeam: 8,
          homeTeamGoals: 2,
          awayTeam: 10,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 14,
          homeTeamGoals: 5,
          awayTeam: 11,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 1,
          homeTeamGoals: 1,
          awayTeam: 16,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 9,
          homeTeamGoals: 3,
          awayTeam: 6,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 10,
          homeTeamGoals: 1,
          awayTeam: 5,
          awayTeamGoals: 3,
          inProgress: false,
        },
        {
          homeTeam: 2,
          homeTeamGoals: 0,
          awayTeam: 7,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 15,
          homeTeamGoals: 0,
          awayTeam: 13,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 14,
          homeTeamGoals: 2,
          awayTeam: 4,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 3,
          homeTeamGoals: 2,
          awayTeam: 11,
          awayTeamGoals: 0,
          inProgress: false,
        },
        {
          homeTeam: 12,
          homeTeamGoals: 4,
          awayTeam: 8,
          awayTeamGoals: 1,
          inProgress: false,
        },
        {
          homeTeam: 16,
          homeTeamGoals: 2,
          awayTeam: 9,
          awayTeamGoals: 0,
          inProgress: true,
        },
        {
          homeTeam: 6,
          homeTeamGoals: 1,
          awayTeam: 1,
          awayTeamGoals: 0,
          inProgress: true,
        },
        {
          homeTeam: 11,
          homeTeamGoals: 0,
          awayTeam: 10,
          awayTeamGoals: 0,
          inProgress: true,
        },
        {
          homeTeam: 7,
          homeTeamGoals: 2,
          awayTeam: 15,
          awayTeamGoals: 2,
          inProgress: true,
        },
        {
          homeTeam: 5,
          homeTeamGoals: 1,
          awayTeam: 3,
          awayTeamGoals: 1,
          inProgress: true,
        },
        {
          homeTeam: 4,
          homeTeamGoals: 1,
          awayTeam: 12,
          awayTeamGoals: 1,
          inProgress: true,
        },
        {
          homeTeam: 8,
          homeTeamGoals: 1,
          awayTeam: 14,
          awayTeamGoals: 2,
          inProgress: true,
        },
        {
          homeTeam: 13,
          homeTeamGoals: 1,
          awayTeam: 2,
          awayTeamGoals: 1,
          inProgress: true,
        }
      ],
      {},
    );
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('matches', null, {});
  },
};
